FROM centos:7

ARG TARGETPLATFORM
ARG BUILDPLATFORM

MAINTAINER Zexi Li <zexi.li@icloud.com>

RUN set -x \
	&& sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Base.repo \
	&& sed -i 's/#baseurl=/baseurl=/g' /etc/yum.repos.d/CentOS-Base.repo \
	&& sed -i 's/mirror.centos.org/vault.centos.org/g' /etc/yum.repos.d/CentOS-Base.repo \
	&& cat /etc/yum.repos.d/CentOS-Base.repo \
	&& yum makecache \
	&& yum install -y git wget \
	&& yum groupinstall -y "Development Tools" \
	&& yum clean all

WORKDIR /opt
RUN set -x \
	&& wget https://dl.google.com/go/go1.21.10.linux-`echo $TARGETPLATFORM | cut -d / -f 2`.tar.gz \
	&& tar xzf go1.21.10.linux-`echo $TARGETPLATFORM | cut -d / -f 2`.tar.gz \
	&& rm -vf  go1.21.10.linux-`echo $TARGETPLATFORM | cut -d / -f 2`.tar.gz

ENV GOROOT="/opt/go"
ENV PATH="/opt/go/bin:${PATH}"

ENV GOPATH="/root/go"
ENV PATH="${GOPATH}/bin:${PATH}"

ENV GOPROXY=https://mirrors.aliyun.com/goproxy/,https://proxy.golang.org,direct

RUN set -x \
	&& mkdir -p "$GOPATH" \
	&& d="$GOPATH/src/golang.org/x/tools" \
	&& mkdir -p "$d" \
	&& git clone --branch yun --depth 4 https://github.com/yousong/tools "$d" \
	&& cd "$d" \
	&& go install ./cmd/goimports

RUN set -x \
	&& mkdir -p "$GOPATH" \
	&& d="$GOPATH/src/yunion.io/x/y18n" \
	&& mkdir -p "$d" \
	&& git clone              --depth 4 https://github.com/yousong/y18n "$d" \
	&& cd "$d" \
	&& go install .

