FROM ubuntu:22.04 AS qga-build

RUN sed -i 's|http://archive.ubuntu.com|http://mirrors.aliyun.com|g' /etc/apt/sources.list
RUN sed -i 's|http://ports.ubuntu.com|http://mirrors.aliyun.com|g' /etc/apt/sources.list

RUN apt-get update
RUN apt-get install -y build-essential gcc make python2 pkg-config flex bison \
        libc6-dev zlib1g-dev libglib2.0-dev libpixman-1-dev
RUN apt-get install -y wget
RUN wget https://download.qemu.org/qemu-4.0.0.tar.xz -P / && tar -xvf /qemu-4.0.0.tar.xz -C /
RUN cd /qemu-4.0.0 && ./configure --disable-xen --target-list=`uname -m`-softmmu --enable-guest-agent --prefix=/ --static --python=python2 && make qemu-ga -j64
RUN cp /qemu-4.0.0/qemu-ga / && rm -rf /qemu-4.0.0*


RUN rm -rf /var/lib/apt/lists
