FROM alpine:3.22.2

LABEL maintainer="Zexi Li <zexi.li@icloud.com>"

RUN sed -i 's!https://dl-cdn.alpinelinux.org/!https://mirrors.ustc.edu.cn/!g' /etc/apk/repositories
RUN sed -i 's!v3.22/!edge/!g' /etc/apk/repositories

RUN apk add alpine-sdk
RUN apk add go=1.25.3-r0
RUN apk add ceph-dev
RUN apk add linux-headers

ENV GOPATH="/root/go"
ENV PATH="${GOPATH}/bin:${PATH}"

RUN set -x \
	&& mkdir -p "$GOPATH" \
	&& d="$GOPATH/src/golang.org/x/tools" \
	&& mkdir -p "$d" \
	&& git clone --depth 4 https://github.com/yunionio/tools "$d" \
	&& cd "$d" \
	&& go install ./cmd/goimports
