FROM nginx:1.29.3
RUN mkdir -p /opt/cloud/yunion/baremetal/baremetal-prepare
RUN curl -L -o /opt/cloud/yunion/baremetal/baremetal-prepare/baremetal_prepare.tar.gz https://iso.yunion.cn/vm-images/baremetal_prepare_202603181.tar.gz
